### ISSUE TITLE
exemptions on container level

### ISSUE THREAD

**Issue by empinator** [cruise-automation/k-rail#132]
Hi,

I am running k-rail on my kubernetes cluster combined with linkerd as service mesh to ensure mTLS communication between pods.
linkerd will automatically inject further (init-)containers into my pod to accomplish this.

One of the injected containers require to be run with `runAsNonRoot: false `
```yaml
...
    image: cr.l5d.io/linkerd/proxy-init:v1.4.0
    imagePullPolicy: IfNotPresent
    name: linkerd-init
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: false
      runAsUser: 0
...
```

then, of course k-rail is throwing a  `pod_no_root_user` violation

I was wondering if there is a way to defne an exemptions for a single container within a pod?

Any help would be much appreciated.
