### ISSUE TITLE
Creating an exemption for a daemonset produces logs with an empty resource

### ISSUE THREAD

**Issue by funkypenguin** [cruise-automation/k-rail#23]
Hey guys,

Trying to use this exemption with the istio-operator:

```
  - resource_name: "istio-cni-node"
    namespace: "istio-system"
    username: "*"
    group: "*"
    exempt_policies: ["pod_trusted_repository", "pod_no_host_network"] 
```

When the operator creates a daemonset, the exemption is applied:

```
{"enforced":false,"kind":"DaemonSet","level":"info","msg":"EXEMPT","namespace":"istio-system","policy":"pod_trusted_repository","resource":"istio-cni-node","time":"2019-10-31T22:05:14Z","user":"system:serviceaccount:istio-system:istio-operator-operator"}
{"enforced":false,"kind":"DaemonSet","level":"info","msg":"EXEMPT","namespace":"istio-system","policy":"pod_no_host_network","resource":"istio-cni-node","time":"2019-10-31T22:05:14Z","user":"system:serviceaccount:istio-system:istio-operator-operator"}
```

But when the daemonset attempts to create pods, the exemption is _not_ applied, since the `resource` value is empty:

```
{"enforced":true,"kind":"Pod","level":"warning","msg":"ENFORCED","namespace":"istio-system","policy":"pod_trusted_repository","resource":"","time":"2019-10-31T22:05:14Z","user":"system:serviceaccount:kube-system:daemon-set-controller"}
{"enforced":true,"kind":"Pod","level":"warning","msg":"ENFORCED","namespace":"istio-system","policy":"pod_no_host_network","resource":"","time":"2019-10-31T22:05:14Z","user":"system:serviceaccount:kube-system:daemon-set-controller"}
```

Is this intended behaviour? :)

Thanks,
D

**Comment by dustin-decker** [comment]
Thanks for the report. This definitely seems like a bug, and not one i've encountered before.

The resource name for a Pod is extracted from the Pod definition: https://github.com/cruise-automation/k-rail/blob/master/resource/pod.go#L48

I'll look into this some more.

Would you be able to provide a simple DaemonSet that could reproduce this?

**Comment by funkypenguin** [comment]
Here's a sample DaemonSet:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bad-daemonset
spec:
  selector:
    matchLabels:
      name: bad
  template:
    metadata:
      labels:
        name: bad
    spec:
      hostNetwork: true
      hostPID: true
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: hostroot
          hostPath:
            path: /
      containers:
        - name: bad
          image: ubuntu
          command: ["sleep", "36000"]
          imagePullPolicy: Always
          volumeMounts:
            - name: dockersock
              mountPath: "/var/run/docker.sock"
            - name: hostroot
              mountPath: "/host"
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN", "SYS_ADMIN"]
```
